name: Health Check
on:
  schedule:
    - cron: "5 * * * *"
jobs:
  job1:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Cypress.io
      uses: cypress-io/github-action@v4.2.0
      with:
          start: npm run test
